### ISSUE TITLE
Link/URL to view training exercise

### ISSUE THREAD

**Issue by BNewing** [mcheung-nhs/accessibility-testing#1]
Hello! Is it hosted anywhere/is there a URL for the exercise? I couldn't see one anywhere on the repo, but might just be missing it. I had a look locally though and it looks good :)

**Comment by mcheung-nhs** [comment]
Hi @BNewing , thanks for having a look! I've not quite finished it yet (need to complete the answer sheet and worksheet) but will hope to do so very soon and then get a URL up and running.

**Comment by BNewing** [comment]
Ah, I'm being too keen! Looking good so far :)

**Comment by mcheung-nhs** [comment]
@BNewing - Finally managed to update the site and get it live: https://nhs-accessibility.herokuapp.com/
Any feedback appreciated!
Thanks.

**Comment by mcheung-nhs** [comment]
Is here now:
https://nhs-accessibility.onrender.com/
